config/routes.rb
Rails.application.routes.draw do


  get 'password_resets/new'

  get 'password_resets/edit'

  root 'pages#home'

  resources :users
  resources :videos
  resources :comments

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :video, VideoUploader
  belongs_to :user
  has_many :comments
  validates :video, presence: true

  validate :video_size

  # has_attached_file :video,
  #       styles: lambda { |a| a.instance.is_image? ? {:small => "x200>", :medium => "x300>", :large => "x400>"}  : {:thumb => { :geometry => "100x100#", :format => 'jpg', :time => 10 }, :medium => { :geometry => "300x300#", :format => 'jpg', :time => 10 }} },
  #           processors: lambda { |a| a.is_video? ? [ :ffmpeg  ] : [ :thumbnail  ]  }

  private

  def video_size
    if video.size > 10.megabytes
      errors.add(:video, "Should be less than 10MB")
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :logged_in_user
  
  def new
  end

  def create
    @video = current_user.videos.build(video_params)
    if @video.save
      redirect_to current_user
    else
      redirect_to current_user
      flash[:danger] = "There was a problem posting the video"
    end
  end

  def show
    @video = Video.find_by(id: params[:id])
    @comments = @video.comments
  end

  private
  def video_params
    params.require(:video).permit(:content, :video)
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_video.html.erb
<li>
   <span class="content">
   <%= video.content %>
   </span>
   <br>
   <span class="video">
       <% if video.video?%>
       <%= video_tag video.video_url.to_s , :controls => true, width: '80%', height: '15%' %>
       <% end %>
   </span> <br>
   <span class="comments">
         <%= link_to fa_icon('comments'), video_path(id: video.id) %> 
         <%= pluralize(video.comments.count, "comment") %>
   </span>
</li>

<script type="text/javascript">
$('#video_video').bind('change', function) {
    size_in_megabytes = this.files[0].size/1024/1024;
    if(size_in_megabytes > 10){
        alert('Maximum file size is 10MB. Choose smaller size')
    }
}
</script>

app/views/videos/new.html.erb
<h1>Videos#new</h1>
<p>Find me in app/views/videos/new.html.erb</p>

app/views/videos/show.html.erb
<% provide(:title, "video")%>
<div class="row">
    <div class="medium-12">
        <div class="medium-8 columns">
            <p><span class="content"><%= @video.content %></span></p>
            <span class="video">
                <% if @video.video?%>
                    <%= video_tag @video.video_url.to_s , :controls => true, width: '80%', height: '15%' %>
                <% end %>
            </span>
        </div>
        <div class="medium-4 columns">
            <h4><strong> Comments</strong></h4>
            <%= form_for(@video.comments.build) do |f|%>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :video_id %>
                <%= f.text_area :content, placeholder: "Add comment ..." %>
                <%= f.submit "comment", class: "button" %>
            <% end %>

        <% if @comments.any?%>
            <ol class="comments">
                <%= render @comments %>
            </ol>
            <% end %>
        </div>
    </div>
</div>