config/routes.rb
Rails.application.routes.draw do


  get 'password_resets/new'

  get 'password_resets/edit'

  root 'pages#home'

  resources :users
  resources :videos
  resources :comments

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/partials/_header.html.erb
<div class="top-bar" sdata-sticky id="widemenu" data-options="marginTop:0;" style="width:100%" data-top-anchor="1">
    <div class="top-bar-left">
        <ul class="menu">
            <li> <%= link_to fa_icon('home', text: "Home", class: 'home'), root_path %></li>
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
            <% unless logged_in? %>
                <li> <%= link_to fa_icon('sign-in', text: "Login"), login_path %></li>
            <% else %>
                <li> <%= link_to fa_icon('users', text: "Users"), users_path %></li>
                <li> <%= link_to fa_icon('mobile', text: "Contact"), '#' %></li>
                <li> <%= link_to fa_icon('user', text: "Profile"), current_user %></li>
                <li> <%= link_to fa_icon('sign-out', text: "Logout"), logout_path, method: :delete %></li>
                <li> <%= link_to fa_icon('settings', text: "Settings"),edit_user_path(current_user) %></li>
            <% end %>

        </ul>
    </div>

</div>

app/views/layouts/partials/_messages.html.erb
<% flash.each do |msg_type, message|%>
    <div id="messages" class="callout <%= msg_type %>">
        <%= message %>
    </div>
<% end %>